import React, { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { SEO } from '../components/SEO';
import { HeroSection } from "../sections/HeroSection";
import { ServicesSection } from "../sections/ServicesSection";
import { PainPointSection } from "../sections/PainPointSection";
import { TestimonialsSection } from "../sections/TestimonialsSection";
import { ProcessSection } from "../sections/ProcessSection";
import { AnalyticsSection } from "../sections/AnalyticsSection";

export function Home() {
  const navigate = useNavigate();

  // ROI Interactive Component State Configuration
  const [hoursSpent, setHoursSpent] = useState<number>(140);
  const [laborCost, setLaborCost] = useState<number>(35);
  const [efficiency, setEfficiency] = useState<number>(50);

  const calculatedSavings = useMemo(() => {
    const defaultCost = hoursSpent * laborCost;
    const monthly = defaultCost * (efficiency / 100);
    return {
      monthly: Math.round(monthly),
      annual: Math.round(monthly * 12)
    };
  }, [hoursSpent, laborCost, efficiency]);

  const handleGetStarted = () => {
    navigate('/contact');
  };

  const handleExploreServices = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    const element = document.getElementById('services-framework');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <>
      <SEO 
        title="Ofstride Services LLP — Intelligent AI Platforms & Agentic Workflows"
        description="Transforming small business operations using high-fidelity automation frameworks, fine-tuned agent infrastructure, and technical consulting."
        canonical="/"
      />
      
      <main>
        {/* Core Sections Wrapper */}
        <HeroSection />
        
        <div id="services-framework">
          <ServicesSection />
        </div>
        
        <PainPointSection />
        
        {/* Modern Interactive ROI Tool Block matching aintric.com analytics panels */}
        <section id="roi-calculator" className="py-24 border-t border-b border-slate-900/60 bg-slate-950/40">
          <div className="container-page max-w-4xl mx-auto px-4">
            <div className="text-center mb-12">
              <span className="text-xs font-bold uppercase tracking-widest text-[#5D7CC1] bg-white/5 border border-white/10 px-3 py-1 rounded-full">
                Value Optimization Engine
              </span>
              <h2 className="text-3xl md:text-4xl font-bold tracking-tight mt-4 text-white">
                Quantify Your Agentic Operational Advantage
              </h2>
              <p className="text-slate-400 text-sm mt-2 max-w-xl mx-auto">
                Fine tune your operational data matrices live to discover resource conservation curves generated by custom autonomous pipelines.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-8 items-stretch">
              {/* Sliders panel */}
              <div className="aintric-card flex flex-col justify-center space-y-6">
                <div>
                  <div className="flex justify-between text-xs font-semibold text-slate-300 mb-2">
                    <span>Monthly Manual Task Hours</span>
                    <span className="text-[#5D7CC1] font-bold">{hoursSpent} Hours</span>
                  </div>
                  <input
                    type="range"
                    min="20"
                    max="500"
                    step="10"
                    value={hoursSpent}
                    onChange={(e) => setHoursSpent(Number(e.target.value))}
                    style={{ width: '100%', accentColor: '#00209F' }}
                  />
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold text-slate-300 mb-2">
                    <span>Fully Burdened Hourly Labor Rate</span>
                    <span className="text-[#5D7CC1] font-bold">${laborCost}/hr</span>
                  </div>
                  <input
                    type="range"
                    min="15"
                    max="150"
                    step="5"
                    value={laborCost}
                    onChange={(e) => setLaborCost(Number(e.target.value))}
                    style={{ width: '100%', accentColor: '#00209F' }}
                  />
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold text-slate-300 mb-2">
                    <span>Target AI Orchestration Rate</span>
                    <span className="text-[#5D7CC1] font-bold">{efficiency}% Automation</span>
                  </div>
                  <input
                    type="range"
                    min="10"
                    max="90"
                    step="5"
                    value={efficiency}
                    onChange={(e) => setEfficiency(Number(e.target.value))}
                    style={{ width: '100%', accentColor: '#00209F' }}
                  />
                </div>
              </div>

              {/* Dynamic Metrics display box */}
              <div className="aintric-card border border-[#A9B9E2]/20 bg-[#00209F]/5 flex flex-col justify-between">
                <div className="space-y-6">
                  <div>
                    <span className="text-[10px] font-bold uppercase tracking-widest text-[#A9B9E2]">Projected Monthly Capital Reclaimed</span>
                    <p className="text-3xl font-black text-white mt-1">${calculatedSavings.monthly.toLocaleString()}</p>
                  </div>
                  <div className="border-t border-slate-800 pt-4">
                    <span className="text-[10px] font-bold uppercase tracking-widest text-[#A9B9E2]">Annual Retained Capital Efficiency</span>
                    <p className="text-4xl font-black text-emerald-400 mt-1">${calculatedSavings.annual.toLocaleString()}</p>
                  </div>
                </div>
                
                <button 
                  onClick={handleGetStarted}
                  className="btn-aintric-primary w-full mt-6 py-3 text-xs uppercase tracking-wider font-bold"
                >
                  Deploy Custom Architecture
                </button>
              </div>
            </div>
          </div>
        </section>

        {/* Dynamic Modernized Conversion Band Area */}
        <section className="py-20 relative overflow-hidden bg-gradient-to-r from-slate-950 via-[#00209F]/10 to-slate-950">
          <div className="container-page grid gap-12 lg:grid-cols-[1.2fr,0.8fr] items-center">
            <div>
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#5D7CC1]">
                System Intake
              </span>
              <h2 className="mt-4 text-3xl md:text-4xl font-bold text-white aintric-gradient-text">
                Ready to Automate Bottlenecks at Scale?
              </h2>
              <p className="mt-4 text-sm text-slate-400 leading-relaxed max-w-xl">
                Let us map your operations to a high-fidelity AI roadmap — custom built, deterministic, and engineered exclusively for small business margin growth.
              </p>
              <div className="mt-8 flex flex-wrap gap-4">
                <button className="btn-aintric-primary" onClick={handleGetStarted}>
                  Book a Consultation
                </button>
                <button className="btn-aintric-secondary" onClick={handleExploreServices}>
                  Explore Services
                </button>
              </div>
            </div>
            
            <div className="grid grid-cols-3 gap-4 text-center">
              <div className="aintric-card p-4 min-h-[110px] flex flex-col justify-center">
                <p className="text-2xl font-black text-white">&lt; 24h</p>
                <p className="mt-1 text-[10px] uppercase tracking-wider text-slate-400">Response SLA</p>
              </div>
              <div className="aintric-card p-4 min-h-[110px] flex flex-col justify-center">
                <p className="text-2xl font-black text-emerald-400">45%+</p>
                <p className="mt-1 text-[10px] uppercase tracking-wider text-slate-400">Avg Efficiency</p>
              </div>
              <div className="aintric-card p-4 min-h-[110px] flex flex-col justify-center">
                <p className="text-2xl font-black text-white">MSME</p>
                <p className="mt-1 text-[10px] uppercase tracking-wider text-slate-400">Optimized</p>
              </div>
            </div>
          </div>
        </section>
        
        <TestimonialsSection />
        <ProcessSection />
        <AnalyticsSection />
      </main>
    </>
  );
}
