import React, { useState, useMemo } from 'react';
import { SEO } from '../components/SEO';
import { HeroSection } from "../sections/HeroSection";
import { ServicesSection } from "../sections/ServicesSection";
import { PainPointSection } from "../sections/PainPointSection";
import { TestimonialsSection } from "../sections/TestimonialsSection";
import { ProcessSection } from "../sections/ProcessSection";
import { AnalyticsSection } from "../sections/AnalyticsSection";

export function Home() {
  // Interactive Calculator State
  const [manualHours, setManualHours] = useState<number>(120);
  const [hourlyCost, setHourlyCost] = useState<number>(30);
  const [efficiencyGain, setEfficiencyGain] = useState<number>(50);

  const roiCalculations = useMemo(() => {
    const baselineCost = manualHours * hourlyCost;
    const monthlySavings = baselineCost * (efficiencyGain / 100);
    const annualSavings = monthlySavings * 12;
    return {
      monthly: Math.round(monthlySavings),
      annual: Math.round(annualSavings)
    };
  }, [manualHours, hourlyCost, efficiencyGain]);

  return (
    <>
      <SEO 
        title="Ofstride Services LLP — Intelligent AI & Agentic Systems for MSMEs"
        description="Transforming small business operations through deterministic agentic systems, operational workflows, and automation consulting."
        canonical="/"
      />
      <main>
        {/* Core Content Delivery Sections */}
        <HeroSection />
        <ServicesSection />
        <PainPointSection />
        
        {/* Dynamic Interactive Small Business ROI Calculator Section */}
        <section id="roi-calculator" className="py-20 bg-slate-100 border-t border-b border-slate-200/70 scroll-margin-top">
          <div className="container-page max-w-4xl mx-auto px-4">
            <div className="text-center mb-10">
              <span className="text-xs font-bold uppercase tracking-widest text-[#5D7CC1] bg-white px-3 py-1 rounded-full border border-slate-200">
                Performance Tool
              </span>
              <h2 className="text-3xl font-bold text-slate-900 tracking-tight mt-3">Quantify Your Automation Advantage</h2>
              <p className="text-slate-500 text-sm mt-1">Adjust sliders to calculate live baseline savings generated by deploying autonomous agents.</p>
            </div>

            <div className="bg-white rounded-2xl p-6 md:p-8 shadow-xl border border-slate-200/60 grid md:grid-cols-2 gap-8">
              {/* Sliders Input Wrapper */}
              <div className="space-y-6">
                <div>
                  <div className="flex justify-between text-xs font-semibold text-slate-700 mb-2">
                    <span>Monthly Manual Task Hours</span>
                    <span className="text-[#00209F] font-bold">{manualHours} Hours</span>
                  </div>
                  <input
                    type="range"
                    min="20"
                    max="500"
                    step="10"
                    value={manualHours}
                    onChange={(e) => setManualHours(Number(e.target.value))}
                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#00209F]"
                  />
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold text-slate-700 mb-2">
                    <span>Fully Burdened Hourly Labor Rate</span>
                    <span className="text-[#00209F] font-bold">${hourlyCost} / hr</span>
                  </div>
                  <input
                    type="range"
                    min="15"
                    max="120"
                    step="5"
                    value={hourlyCost}
                    onChange={(e) => setHourlyCost(Number(e.target.value))}
                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#00209F]"
                  />
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold text-slate-700 mb-2">
                    <span>Target AI Automation Rate</span>
                    <span className="text-[#00209F] font-bold">{efficiencyGain}% Automation</span>
                  </div>
                  <input
                    type="range"
                    min="10"
                    max="90"
                    step="5"
                    value={efficiencyGain}
                    onChange={(e) => setEfficiencyGain(Number(e.target.value))}
                    className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#00209F]"
                  />
                </div>
              </div>

              {/* Dynamic Outcomes Cards */}
              <div className="bg-[#A9B9E2]/10 border border-[#A9B9E2]/50 rounded-xl p-6 flex flex-col justify-between">
                <div className="space-y-5">
                  <div>
                    <span className="text-[10px] font-bold uppercase tracking-widest text-[#5D7CC1]">Projected Monthly Capital Reclaimed</span>
                    <p className="text-3xl font-black text-[#00209F] mt-1">${roiCalculations.monthly.toLocaleString()}</p>
                  </div>
                  <div className="border-t border-[#A9B9E2]/30 pt-4">
                    <span className="text-[10px] font-bold uppercase tracking-widest text-[#5D7CC1]">Annual Retained Capital Efficiency</span>
                    <p className="text-4xl font-black text-emerald-600 mt-1">${roiCalculations.annual.toLocaleString()}</p>
                  </div>
                </div>
                <div className="text-[11px] text-slate-500 mt-6 pt-3 border-t border-[#A9B9E2]/20 italic">
                  *Estimates assume deterministic orchestrations optimized for operations teams.
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Central Strategy Conversion Band */}
        <section className="bg-gradient-to-br from-[#00209F] to-[#2042be] py-16 text-white relative overflow-hidden">
          <div className="container-page grid gap-8 lg:grid-cols-[1.15fr,0.85fr] items-center px-4">
            <div className="max-w-2xl">
              <p className="text-xs font-bold uppercase tracking-[0.25em] text-[#A9B9E2]">
                Start a Conversation
              </p>
              <h2 className="mt-3 text-3xl font-black leading-tight sm:text-4xl text-white">Ready to Deploy Deterministic AI?</h2>
              <p className="mt-3 text-sm text-slate-200 leading-relaxed">
                Let us map your systemic workflow blockers into a practical, resilient automation roadmap—engineered exclusively for measurable corporate momentum.
              </p>
              <div className="mt-6 flex flex-wrap gap-3">
                <a className="inline-flex items-center justify-center text-xs font-bold px-5 py-3 rounded-xl bg-white text-[#00209F] hover:bg-slate-100 transition-transform hover:-translate-y-0.5 shadow" href="/contact">
                  Book Architecture Consultation
                </a>
                <a className="inline-flex items-center justify-center text-xs font-bold px-5 py-3 rounded-xl border border-white/30 text-white hover:bg-white/10 transition-colors" href="#services">
                  Explore Ecosystem
                </a>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-4 text-center">
              <div className="bg-white/5 border border-white/10 rounded-xl p-4 flex flex-col justify-center min-h-[110px]">
                <p className="text-2xl font-black text-white">&lt; 24h</p>
                <p className="mt-1 text-[11px] uppercase tracking-wider text-[#A9B9E2]">SLA Response</p>
              </div>
              <div className="bg-white/5 border border-white/10 rounded-xl p-4 flex flex-col justify-center min-h-[110px]">
                <p className="text-2xl font-black text-emerald-400">45%+</p>
                <p className="mt-1 text-[11px] uppercase tracking-wider text-[#A9B9E2]">Avg Efficiency</p>
              </div>
              <div className="bg-white/5 border border-white/10 rounded-xl p-4 flex flex-col justify-center min-h-[110px]">
                <p className="text-2xl font-black text-white">Production</p>
                <p className="mt-1 text-[11px] uppercase tracking-wider text-[#A9B9E2]">Ready Stack</p>
              </div>
            </div>
          </div>
        </section>
        
        <TestimonialsSection />
        <ProcessSection />
        <AnalyticsSection />
      </main>
    </>
  );
}
